version: '3'
services:
  acacia-front:
    container_name: acacia-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8080"
    volumes:
    - .:/app
    - /app/node_modules