version: '3'
services:
  acacia-front:
    container_name: acacia-frontend
    env_file: .env-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run serve"
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    - /app/node_modules