
name: deploy-staging

on: 
  push:
    branches:
      - develop
      - release/*
      - feature/179-continuous-deploy

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
    - name: Docker build
      run: docker build -t acaciaelis/acacia:node-staging .
    - name: Docker push
      run: docker push acaciaelis/acacia:node-staging