
name: CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: setup environment
      run: docker-compose up -d --build
    - name: Run tests
      run: docker exec acacia-frontend npm run test:unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
    - name: Build
      run: docker exec acacia-frontend npm run build
          
