name: test

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: setup environment
      run: docker-compose up -d --build
    - name: Run tests
      run: docker exec acacia-frontend npm run test:unit
